#!/usr/bin/env python3

import socket
import os
import sys
import signal


s=socket.socket(socket.AF_INET,socket.SOCK_STREAM) # TCP socket
s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1) # aby sme mohli ihned restartovat server
s.bind(('',9999))
s.listen(5)
signal.signal(signal.SIGCHLD,signal.SIG_IGN) # aby nezostavali zombie procesy
while True:
    connected_socket,client_addr=s.accept()
    print(f'Pripojil sa klient: {client_addr}')
    pid_chld=os.fork()
    # 2 procesy
    if pid_chld==0:
        # Child
        s.close()
        while True:
            bs=connected_socket.recv(1024)
            if not bs: 
                print(f'klient {client_addr} uzavrel spojenie')
                break
            print(bs)
            connected_socket.send(b'bum!\n')
        sys.exit(0) 
    else:
        connected_socket.close()




